name: Playwright Tests

on:
  workflow_dispatch:
  push:
    branches:
      main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      
      
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Playwright Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-ms-playwright-${{ hashFiles('**/build.gradle') }}
      
      - name: Grant Permissions to gradlew
        run: chmod +x gradlew
      
#       - name: Test
#         run: ./gradlew clean test  --info -Dheadless=false -Dbrowser=chrome
      - name: Run Front End Tests
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: clean test --info -Dheadless=false -Dbrowser=chrome
