name: Playwright Tests

on:
  workflow_dispatch:
  push:
    branches:
      main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      
      
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

#       - name: Playwright Cache
#         uses: actions/cache@v3
#         with:
#           path: |
#             ~/.cache/ms-playwright
#           key: ${{ runner.os }}-ms-playwright-${{ hashFiles('**/build.gradle') }}
      
      - name: Grant Permissions to gradlew
        run: chmod +x gradlew
      
      - name: Set up virtual X11
        run: sudo apt-get install xvfb
      
      - name: Start virtual frame buffer
        run: Xvfb :19 -screen 0 1024x768x16 &
      
      - name: set display
        run: export DISPLAY=:19
      
      - name: Build with Gradle
        run: gradle clean test  
       
      - name: Archive Rest Results
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: test-results
          path: GradleReports/emailable-report.html
